Frozen autocommit 2024-07-02 02:40:14.338784

diff --git a/fips-mode-setup b/fips-mode-setup
--- a/fips-mode-setup
+++ b/fips-mode-setup
@@ -60,7 +60,7 @@ while test $# -ge 1 ; do
 done
 
 if test $usage = 1 -o x$enable_fips = x ; then
-	echo "Check, enable, or disable the system FIPS mode."
+	echo "Check, enable, or disable (unsupported) the system FIPS mode."
 	echo "usage: $0 --enable|--disable [--no-bootcfg]"
 	echo "usage: $0 --check"
 	echo "usage: $0 --is-enabled"
@@ -182,6 +182,31 @@ if test "$boot_config" = 1 && test -z "$(ls -A /boot)" ; then
 	echo >&2 "/boot directory is empty, FIPS mode cannot be $(enable2txt $enable_fips)."
 	echo >&2 "If you want to configure the bootloader manually, re-run with --no-bootcfg."
 	exit 1
+fi
+
+if test "$FIPS_MODE_SETUP_SKIP_WARNING" != 1 ; then
+	if test $enable_fips = 1 ; then
+		echo >&2 "*****************************************************************"
+		echo >&2 "* PRESS CONTROL-C WITHIN 15 SECONDS TO ABORT...                 *"
+		echo >&2 "*                                                               *"
+		echo >&2 "* ENABLING FIPS MODE AFTER THE INSTALLATION IS NOT RECOMMENDED. *"
+		echo >&2 "* THIS OPERATION CANNOT BE UNDONE.                              *"
+		echo >&2 "* REINSTALL WITH fips=1 INSTEAD.                                *"
+		echo >&2 "*****************************************************************"
+	elif test $enable_fips = 0 ; then
+		echo >&2 "*****************************************************************"
+		echo >&2 "* PRESS CONTROL-C WITHIN 15 SECONDS TO ABORT...                 *"
+		echo >&2 "*                                                               *"
+		echo >&2 "* DISABLING FIPS MODE AFTER THE INSTALLATION IS NOT SUPPORTED.  *"
+		echo >&2 "* THIS OPERATION CANNOT BE UNDONE.                              *"
+		echo >&2 "* WIPE ALL MEDIA AND REINSTALL WITHOUT fips=1 INSTEAD.          *"
+		echo >&2 "*****************************************************************"
+	fi
+	for i in {15..1}; do
+		echo >&2 -n "$i... "
+		sleep 1 || exit 77
+	done
+	echo >&2
 fi
 
 if test $enable_fips = 1 ; then
